/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bigdaddyplayer;

/**
 *
 * @author root
 */
public class SetDetail extends javax.swing.JFrame {
    String name,artist,album,genre,comment;
    int rating;
    String location;
    DbSave SaveDet = new DbSave();
    boolean sharing;
    /**
     * Creates new form SetDetail
     * @param loc
     */
    public SetDetail(String loc) {
        initComponents();
        location = loc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tartist = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        talbum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tratting = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        tgenre = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcomment = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tsharing = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set Detail");
        setBackground(new java.awt.Color(0, 51, 153));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 97, 34));

        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 37, 190, 38));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Artist");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 97, -1));

        tartist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tartistActionPerformed(evt);
            }
        });
        getContentPane().add(tartist, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 81, 190, 42));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Album");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 91, 32));

        talbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talbumActionPerformed(evt);
            }
        });
        getContentPane().add(talbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 129, 190, 42));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Rating");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 48, 31));

        tratting.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(tratting, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 217, 58, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Genre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 212, 46, 31));

        tgenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pop", "Hip Hop", "Jazz", "Rock", "Folk", "Blues", "Electro", "R&B", "Rap", "Country", "EDM", "Other" }));
        getContentPane().add(tgenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 214, -1, -1));

        jScrollPane1.setViewportView(tcomment);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 261, 263, 146));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Comment");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, 34));

        jButton1.setText("Save");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 425, -1, -1));

        tsharing.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tsharing.setForeground(new java.awt.Color(0, 102, 102));
        tsharing.setText("Sharing");
        tsharing.setOpaque(false);
        getContentPane().add(tsharing, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 215, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigdaddyplayer/images/background_white_by_themrsnowman13-d4h17rj.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void talbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_talbumActionPerformed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void tartistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tartistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tartistActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        name = tname.getText() + "";
        artist = tartist.getText() + "";
        album = talbum.getText() + "";
        rating = (int) tratting.getValue();
        genre = tgenre.getSelectedItem() + "";
        sharing = tsharing.isEnabled();
        comment = tcomment.getText() + "";
        System.out.println(sharing);
        
        SaveDet.set_detail(location, name, artist, album, rating, genre, comment);
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField talbum;
    private javax.swing.JTextField tartist;
    private javax.swing.JTextPane tcomment;
    private javax.swing.JComboBox<String> tgenre;
    private javax.swing.JTextField tname;
    private javax.swing.JSpinner tratting;
    private javax.swing.JRadioButton tsharing;
    // End of variables declaration//GEN-END:variables
}
